services:
    # Service declaration into symfony2 with translator and router
    acme.js_vars:
        class: Alcalyn\JsVars\JsVars
        calls:
            - [ enableTranslator, [ @translator ]]
            - [ enableRouter, [ @router ]]

    # Listener declaration into Symfony2 to declare global variables to pass to all views
    acme.listener.js_vars_initialize:
        class: Acme\AppBundle\Listener\JsVarsInitializeListener
        arguments: [ @acme.js_vars, %kernel.debug% ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
